/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddPaymentGroupAndPaymentAffiliationsByManagementGroupIdRequestPaymentAffiliationsInner } from './add-payment-group-and-payment-affiliations-by-management-group-id-request-payment-affiliations-inner';
// May contain unused imports in some cases
// @ts-ignore
import { AddPaymentGroupAndPaymentAffiliationsByManagementGroupIdRequestPaymentGroup } from './add-payment-group-and-payment-affiliations-by-management-group-id-request-payment-group';

/**
 * 
 * @export
 * @interface AddPaymentGroupAndPaymentAffiliationsByManagementGroupIdRequest
 */
export interface AddPaymentGroupAndPaymentAffiliationsByManagementGroupIdRequest {
    /**
     * 
     * @type {AddPaymentGroupAndPaymentAffiliationsByManagementGroupIdRequestPaymentGroup}
     * @memberof AddPaymentGroupAndPaymentAffiliationsByManagementGroupIdRequest
     */
    'payment_group': AddPaymentGroupAndPaymentAffiliationsByManagementGroupIdRequestPaymentGroup;
    /**
     * 支払グループの所属情報の配列
     * @type {Array<AddPaymentGroupAndPaymentAffiliationsByManagementGroupIdRequestPaymentAffiliationsInner>}
     * @memberof AddPaymentGroupAndPaymentAffiliationsByManagementGroupIdRequest
     */
    'payment_affiliations': Array<AddPaymentGroupAndPaymentAffiliationsByManagementGroupIdRequestPaymentAffiliationsInner>;
}

