/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddPaymentAffiliationsByManagementGroupIdAndPaymentGroupIdRequestInner
 */
export interface AddPaymentAffiliationsByManagementGroupIdAndPaymentGroupIdRequestInner {
    /**
     * ユーザーID
     * @type {string}
     * @memberof AddPaymentAffiliationsByManagementGroupIdAndPaymentGroupIdRequestInner
     */
    'user_id': string;
    /**
     * 支払割合
     * @type {number}
     * @memberof AddPaymentAffiliationsByManagementGroupIdAndPaymentGroupIdRequestInner
     */
    'ratio': number;
}

