/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AddPaymentRelationByManagementGroupIdRequestAffiliationsInner } from './add-payment-relation-by-management-group-id-request-affiliations-inner';
// May contain unused imports in some cases
// @ts-ignore
import { AddPaymentRelationByManagementGroupIdRequestGroup } from './add-payment-relation-by-management-group-id-request-group';

/**
 * 
 * @export
 * @interface AddPaymentRelationByManagementGroupIdRequest
 */
export interface AddPaymentRelationByManagementGroupIdRequest {
    /**
     * 
     * @type {AddPaymentRelationByManagementGroupIdRequestGroup}
     * @memberof AddPaymentRelationByManagementGroupIdRequest
     */
    'group': AddPaymentRelationByManagementGroupIdRequestGroup;
    /**
     * 支払グループの所属情報の配列
     * @type {Array<AddPaymentRelationByManagementGroupIdRequestAffiliationsInner>}
     * @memberof AddPaymentRelationByManagementGroupIdRequest
     */
    'affiliations': Array<AddPaymentRelationByManagementGroupIdRequestAffiliationsInner>;
}

