/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddDebtRecordsRequestInner
 */
export interface AddDebtRecordsRequestInner {
    /**
     * 貸主ID
     * @type {number}
     * @memberof AddDebtRecordsRequestInner
     */
    'lending_user_id': number;
    /**
     * 借主ID
     * @type {number}
     * @memberof AddDebtRecordsRequestInner
     */
    'borrowing_user_id': number;
    /**
     * 金額
     * @type {number}
     * @memberof AddDebtRecordsRequestInner
     */
    'amount_of_money': number;
    /**
     * 説明
     * @type {string}
     * @memberof AddDebtRecordsRequestInner
     */
    'description': string;
    /**
     * 取引日
     * @type {string}
     * @memberof AddDebtRecordsRequestInner
     */
    'transacted_on': string;
}

