/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 借金履歴及び借主名
 * @export
 * @interface BorrowingUserDebtRecord
 */
export interface BorrowingUserDebtRecord {
    /**
     * 借金履歴ID
     * @type {number}
     * @memberof BorrowingUserDebtRecord
     */
    'id': number;
    /**
     * 借主名
     * @type {number}
     * @memberof BorrowingUserDebtRecord
     */
    'borrowing_user_name': number;
    /**
     * 金額
     * @type {number}
     * @memberof BorrowingUserDebtRecord
     */
    'amount_of_money': number;
    /**
     * 説明
     * @type {string}
     * @memberof BorrowingUserDebtRecord
     */
    'description': string;
    /**
     * 取引日
     * @type {string}
     * @memberof BorrowingUserDebtRecord
     */
    'transacted_on': string;
}

