/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { BulkInsertExpenseWithDebtRecordsByPaymentGroupIdRequestExpensesInner } from './bulk-insert-expense-with-debt-records-by-payment-group-id-request-expenses-inner';

/**
 * 
 * @export
 * @interface BulkInsertExpenseWithDebtRecordsByPaymentGroupIdRequest
 */
export interface BulkInsertExpenseWithDebtRecordsByPaymentGroupIdRequest {
    /**
     * 
     * @type {Array<BulkInsertExpenseWithDebtRecordsByPaymentGroupIdRequestExpensesInner>}
     * @memberof BulkInsertExpenseWithDebtRecordsByPaymentGroupIdRequest
     */
    'expenses': Array<BulkInsertExpenseWithDebtRecordsByPaymentGroupIdRequestExpensesInner>;
}

