/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BulkInsertExpensesByManagementGroupIdAndPaymentGroupIdRequestExpensesInner
 */
export interface BulkInsertExpensesByManagementGroupIdAndPaymentGroupIdRequestExpensesInner {
    /**
     * ユーザーID
     * @type {string}
     * @memberof BulkInsertExpensesByManagementGroupIdAndPaymentGroupIdRequestExpensesInner
     */
    'user_id': string;
    /**
     * 金額
     * @type {number}
     * @memberof BulkInsertExpensesByManagementGroupIdAndPaymentGroupIdRequestExpensesInner
     */
    'amount_of_money': number;
    /**
     * 説明
     * @type {string}
     * @memberof BulkInsertExpensesByManagementGroupIdAndPaymentGroupIdRequestExpensesInner
     */
    'description': string;
    /**
     * 支払日
     * @type {string}
     * @memberof BulkInsertExpensesByManagementGroupIdAndPaymentGroupIdRequestExpensesInner
     */
    'paid_on': string;
}

