/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PaymentGroup } from './payment-group';
// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * 費用
 * @export
 * @interface Expense
 */
export interface Expense {
    /**
     * 費用ID
     * @type {string}
     * @memberof Expense
     */
    'id': string;
    /**
     * 
     * @type {User}
     * @memberof Expense
     */
    'user': User;
    /**
     * 
     * @type {PaymentGroup}
     * @memberof Expense
     */
    'payment_group': PaymentGroup;
    /**
     * 金額
     * @type {number}
     * @memberof Expense
     */
    'amount_of_money': number;
    /**
     * 説明
     * @type {string}
     * @memberof Expense
     */
    'description': string;
    /**
     * 支払日
     * @type {string}
     * @memberof Expense
     */
    'paid_on': string;
    /**
     * 返済状況
     * @type {boolean}
     * @memberof Expense
     */
    'is_paid': boolean;
}

