/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 管理グループに所属するユーザー
 * @export
 * @interface ManagementAffiliationUser
 */
export interface ManagementAffiliationUser {
    /**
     * 管理グループ所属ID
     * @type {number}
     * @memberof ManagementAffiliationUser
     */
    'id': number;
    /**
     * ユーザー名
     * @type {string}
     * @memberof ManagementAffiliationUser
     */
    'user_name': string;
}

