/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 支払グループに所属するユーザー
 * @export
 * @interface PaymentAffiliationUser
 */
export interface PaymentAffiliationUser {
    /**
     * 支払グループ所属ID
     * @type {number}
     * @memberof PaymentAffiliationUser
     */
    'id': number;
    /**
     * ユーザー名
     * @type {string}
     * @memberof PaymentAffiliationUser
     */
    'name': string;
    /**
     * 支払割合
     * @type {number}
     * @memberof PaymentAffiliationUser
     */
    'ratio': number;
}

