/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PaymentAffiliation } from './payment-affiliation';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentGroup } from './payment-group';

/**
 * 支払グループと支払グループ所属情報の配列
 * @export
 * @interface PaymentGroupAndPaymentAffiliations
 */
export interface PaymentGroupAndPaymentAffiliations {
    /**
     * 
     * @type {PaymentGroup}
     * @memberof PaymentGroupAndPaymentAffiliations
     */
    'payment_group': PaymentGroup;
    /**
     * 
     * @type {Array<PaymentAffiliation>}
     * @memberof PaymentGroupAndPaymentAffiliations
     */
    'payment_affiliations': Array<PaymentAffiliation>;
}

