/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 支払グループ
 * @export
 * @interface PaymentGroup
 */
export interface PaymentGroup {
    /**
     * 支払グループID
     * @type {string}
     * @memberof PaymentGroup
     */
    'id': string;
    /**
     * 支払グループ名
     * @type {string}
     * @memberof PaymentGroup
     */
    'name': string;
}

