/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { User } from './user';

/**
 * 支払グループ所属情報
 * @export
 * @interface PaymentAffiliation
 */
export interface PaymentAffiliation {
    /**
     * 
     * @type {User}
     * @memberof PaymentAffiliation
     */
    'user': User;
    /**
     * 支払割合
     * @type {number}
     * @memberof PaymentAffiliation
     */
    'ratio': number;
}

