/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * エラー
 * @export
 * @interface ResponseError
 */
export interface ResponseError {
    /**
     * エラーメッセージ
     * @type {Array<string>}
     * @memberof ResponseError
     */
    'messages': Array<string>;
}

