/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 総貸借
 * @export
 * @interface TotalBorrowingAndLending
 */
export interface TotalBorrowingAndLending {
    /**
     * ユーザーID
     * @type {string}
     * @memberof TotalBorrowingAndLending
     */
    'user_id': string;
    /**
     * 総貸借
     * @type {number}
     * @memberof TotalBorrowingAndLending
     */
    'amount_of_money': number;
}

