/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 借金履歴及びユーザー名
 * @export
 * @interface UserDebtRecord
 */
export interface UserDebtRecord {
    /**
     * 借金履歴ID
     * @type {string}
     * @memberof UserDebtRecord
     */
    'id': string;
    /**
     * 貸主名
     * @type {string}
     * @memberof UserDebtRecord
     */
    'lending_user_name': string;
    /**
     * 借主名
     * @type {string}
     * @memberof UserDebtRecord
     */
    'borrowing_user_name': string;
    /**
     * 金額
     * @type {number}
     * @memberof UserDebtRecord
     */
    'amount_of_money': number;
    /**
     * 説明
     * @type {string}
     * @memberof UserDebtRecord
     */
    'description': string;
    /**
     * 取引日
     * @type {string}
     * @memberof UserDebtRecord
     */
    'transacted_on': string;
}

