/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AddManagementGroupRequest } from '../model';
// @ts-ignore
import { ManagementGroup } from '../model';
/**
 * ManagementGroupApi - axios parameter creator
 * @export
 */
export const ManagementGroupApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 管理グループを作成する
         * @summary 管理グループを作成
         * @param {AddManagementGroupRequest} [addManagementGroupRequest] リクエスト用の管理グループ
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addManagementGroup: async (addManagementGroupRequest?: AddManagementGroupRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/management_groups`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            await setApiKeyToObject(localVarHeaderParameter, "access-token", configuration)

            // authentication client required
            await setApiKeyToObject(localVarHeaderParameter, "client", configuration)

            // authentication uid required
            await setApiKeyToObject(localVarHeaderParameter, "uid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addManagementGroupRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 管理グループを取得する
         * @summary 管理グループを取得
         * @param {number} managementGroupId 管理グループID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getManagementGroupByManagementGroupId: async (managementGroupId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'managementGroupId' is not null or undefined
            assertParamExists('getManagementGroupByManagementGroupId', 'managementGroupId', managementGroupId)
            const localVarPath = `/management_groups/{management_group_id}`
                .replace(`{${"management_group_id"}}`, encodeURIComponent(String(managementGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            await setApiKeyToObject(localVarHeaderParameter, "access-token", configuration)

            // authentication client required
            await setApiKeyToObject(localVarHeaderParameter, "client", configuration)

            // authentication uid required
            await setApiKeyToObject(localVarHeaderParameter, "uid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ユーザーに紐づく全ての管理グループを取得する
         * @summary ユーザーに紐づく全ての管理グループを取得
         * @param {number} userId ユーザーID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getManagementGroupsByUserId: async (userId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getManagementGroupsByUserId', 'userId', userId)
            const localVarPath = `/users/{user_id}/management_groups`
                .replace(`{${"user_id"}}`, encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            await setApiKeyToObject(localVarHeaderParameter, "access-token", configuration)

            // authentication client required
            await setApiKeyToObject(localVarHeaderParameter, "client", configuration)

            // authentication uid required
            await setApiKeyToObject(localVarHeaderParameter, "uid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ManagementGroupApi - functional programming interface
 * @export
 */
export const ManagementGroupApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ManagementGroupApiAxiosParamCreator(configuration)
    return {
        /**
         * 管理グループを作成する
         * @summary 管理グループを作成
         * @param {AddManagementGroupRequest} [addManagementGroupRequest] リクエスト用の管理グループ
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addManagementGroup(addManagementGroupRequest?: AddManagementGroupRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ManagementGroup>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addManagementGroup(addManagementGroupRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 管理グループを取得する
         * @summary 管理グループを取得
         * @param {number} managementGroupId 管理グループID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getManagementGroupByManagementGroupId(managementGroupId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ManagementGroup>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getManagementGroupByManagementGroupId(managementGroupId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * ユーザーに紐づく全ての管理グループを取得する
         * @summary ユーザーに紐づく全ての管理グループを取得
         * @param {number} userId ユーザーID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getManagementGroupsByUserId(userId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ManagementGroup>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getManagementGroupsByUserId(userId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ManagementGroupApi - factory interface
 * @export
 */
export const ManagementGroupApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ManagementGroupApiFp(configuration)
    return {
        /**
         * 管理グループを作成する
         * @summary 管理グループを作成
         * @param {AddManagementGroupRequest} [addManagementGroupRequest] リクエスト用の管理グループ
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addManagementGroup(addManagementGroupRequest?: AddManagementGroupRequest, options?: any): AxiosPromise<ManagementGroup> {
            return localVarFp.addManagementGroup(addManagementGroupRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 管理グループを取得する
         * @summary 管理グループを取得
         * @param {number} managementGroupId 管理グループID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getManagementGroupByManagementGroupId(managementGroupId: number, options?: any): AxiosPromise<ManagementGroup> {
            return localVarFp.getManagementGroupByManagementGroupId(managementGroupId, options).then((request) => request(axios, basePath));
        },
        /**
         * ユーザーに紐づく全ての管理グループを取得する
         * @summary ユーザーに紐づく全ての管理グループを取得
         * @param {number} userId ユーザーID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getManagementGroupsByUserId(userId: number, options?: any): AxiosPromise<Array<ManagementGroup>> {
            return localVarFp.getManagementGroupsByUserId(userId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ManagementGroupApi - object-oriented interface
 * @export
 * @class ManagementGroupApi
 * @extends {BaseAPI}
 */
export class ManagementGroupApi extends BaseAPI {
    /**
     * 管理グループを作成する
     * @summary 管理グループを作成
     * @param {AddManagementGroupRequest} [addManagementGroupRequest] リクエスト用の管理グループ
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagementGroupApi
     */
    public addManagementGroup(addManagementGroupRequest?: AddManagementGroupRequest, options?: AxiosRequestConfig) {
        return ManagementGroupApiFp(this.configuration).addManagementGroup(addManagementGroupRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 管理グループを取得する
     * @summary 管理グループを取得
     * @param {number} managementGroupId 管理グループID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagementGroupApi
     */
    public getManagementGroupByManagementGroupId(managementGroupId: number, options?: AxiosRequestConfig) {
        return ManagementGroupApiFp(this.configuration).getManagementGroupByManagementGroupId(managementGroupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ユーザーに紐づく全ての管理グループを取得する
     * @summary ユーザーに紐づく全ての管理グループを取得
     * @param {number} userId ユーザーID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ManagementGroupApi
     */
    public getManagementGroupsByUserId(userId: number, options?: AxiosRequestConfig) {
        return ManagementGroupApiFp(this.configuration).getManagementGroupsByUserId(userId, options).then((request) => request(this.axios, this.basePath));
    }
}
