/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { AddPaymentAffiliationsByPaymentGroupIdRequestInner } from '../model';
// @ts-ignore
import { PaymentAffiliationUser } from '../model';
/**
 * PaymentAffiliationApi - axios parameter creator
 * @export
 */
export const PaymentAffiliationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 支払グループに複数のユーザーを所属させる
         * @summary 支払グループに複数のユーザーを所属させる
         * @param {number} paymentGroupId 支払グループID
         * @param {Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>} [addPaymentAffiliationsByPaymentGroupIdRequestInner] リクエスト用の支払グループの所属情報の配列
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPaymentAffiliationsByPaymentGroupId: async (paymentGroupId: number, addPaymentAffiliationsByPaymentGroupIdRequestInner?: Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paymentGroupId' is not null or undefined
            assertParamExists('addPaymentAffiliationsByPaymentGroupId', 'paymentGroupId', paymentGroupId)
            const localVarPath = `/payment_groups/{payment_group_id}/payment_affiliations/bulk_insert`
                .replace(`{${"payment_group_id"}}`, encodeURIComponent(String(paymentGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            await setApiKeyToObject(localVarHeaderParameter, "access-token", configuration)

            // authentication client required
            await setApiKeyToObject(localVarHeaderParameter, "client", configuration)

            // authentication uid required
            await setApiKeyToObject(localVarHeaderParameter, "uid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addPaymentAffiliationsByPaymentGroupIdRequestInner, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 支払グループに所属する全てのユーザーを取得する
         * @summary 支払グループに所属する全てのユーザーを取得
         * @param {number} paymentGroupId 支払グループID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPaymentAffiliationUsersByPaymentGroupId: async (paymentGroupId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paymentGroupId' is not null or undefined
            assertParamExists('getPaymentAffiliationUsersByPaymentGroupId', 'paymentGroupId', paymentGroupId)
            const localVarPath = `/payment_groups/{payment_group_id}/payment_affiliation_users`
                .replace(`{${"payment_group_id"}}`, encodeURIComponent(String(paymentGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            await setApiKeyToObject(localVarHeaderParameter, "access-token", configuration)

            // authentication client required
            await setApiKeyToObject(localVarHeaderParameter, "client", configuration)

            // authentication uid required
            await setApiKeyToObject(localVarHeaderParameter, "uid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 複数のユーザーの支払グループへの所属情報を更新する
         * @summary 複数のユーザーの支払グループへの所属情報を更新
         * @param {number} paymentGroupId 支払グループID
         * @param {Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>} [addPaymentAffiliationsByPaymentGroupIdRequestInner] リクエスト用の支払グループの所属情報の配列
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePaymentAffiliationsByPaymentGroupId: async (paymentGroupId: number, addPaymentAffiliationsByPaymentGroupIdRequestInner?: Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'paymentGroupId' is not null or undefined
            assertParamExists('updatePaymentAffiliationsByPaymentGroupId', 'paymentGroupId', paymentGroupId)
            const localVarPath = `/payment_groups/{payment_group_id}/payment_affiliations/bulk_update`
                .replace(`{${"payment_group_id"}}`, encodeURIComponent(String(paymentGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            await setApiKeyToObject(localVarHeaderParameter, "access-token", configuration)

            // authentication client required
            await setApiKeyToObject(localVarHeaderParameter, "client", configuration)

            // authentication uid required
            await setApiKeyToObject(localVarHeaderParameter, "uid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(addPaymentAffiliationsByPaymentGroupIdRequestInner, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentAffiliationApi - functional programming interface
 * @export
 */
export const PaymentAffiliationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentAffiliationApiAxiosParamCreator(configuration)
    return {
        /**
         * 支払グループに複数のユーザーを所属させる
         * @summary 支払グループに複数のユーザーを所属させる
         * @param {number} paymentGroupId 支払グループID
         * @param {Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>} [addPaymentAffiliationsByPaymentGroupIdRequestInner] リクエスト用の支払グループの所属情報の配列
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addPaymentAffiliationsByPaymentGroupId(paymentGroupId: number, addPaymentAffiliationsByPaymentGroupIdRequestInner?: Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PaymentAffiliationUser>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addPaymentAffiliationsByPaymentGroupId(paymentGroupId, addPaymentAffiliationsByPaymentGroupIdRequestInner, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 支払グループに所属する全てのユーザーを取得する
         * @summary 支払グループに所属する全てのユーザーを取得
         * @param {number} paymentGroupId 支払グループID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPaymentAffiliationUsersByPaymentGroupId(paymentGroupId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PaymentAffiliationUser>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPaymentAffiliationUsersByPaymentGroupId(paymentGroupId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 複数のユーザーの支払グループへの所属情報を更新する
         * @summary 複数のユーザーの支払グループへの所属情報を更新
         * @param {number} paymentGroupId 支払グループID
         * @param {Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>} [addPaymentAffiliationsByPaymentGroupIdRequestInner] リクエスト用の支払グループの所属情報の配列
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePaymentAffiliationsByPaymentGroupId(paymentGroupId: number, addPaymentAffiliationsByPaymentGroupIdRequestInner?: Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<PaymentAffiliationUser>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePaymentAffiliationsByPaymentGroupId(paymentGroupId, addPaymentAffiliationsByPaymentGroupIdRequestInner, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PaymentAffiliationApi - factory interface
 * @export
 */
export const PaymentAffiliationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentAffiliationApiFp(configuration)
    return {
        /**
         * 支払グループに複数のユーザーを所属させる
         * @summary 支払グループに複数のユーザーを所属させる
         * @param {number} paymentGroupId 支払グループID
         * @param {Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>} [addPaymentAffiliationsByPaymentGroupIdRequestInner] リクエスト用の支払グループの所属情報の配列
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addPaymentAffiliationsByPaymentGroupId(paymentGroupId: number, addPaymentAffiliationsByPaymentGroupIdRequestInner?: Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>, options?: any): AxiosPromise<Array<PaymentAffiliationUser>> {
            return localVarFp.addPaymentAffiliationsByPaymentGroupId(paymentGroupId, addPaymentAffiliationsByPaymentGroupIdRequestInner, options).then((request) => request(axios, basePath));
        },
        /**
         * 支払グループに所属する全てのユーザーを取得する
         * @summary 支払グループに所属する全てのユーザーを取得
         * @param {number} paymentGroupId 支払グループID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPaymentAffiliationUsersByPaymentGroupId(paymentGroupId: number, options?: any): AxiosPromise<Array<PaymentAffiliationUser>> {
            return localVarFp.getPaymentAffiliationUsersByPaymentGroupId(paymentGroupId, options).then((request) => request(axios, basePath));
        },
        /**
         * 複数のユーザーの支払グループへの所属情報を更新する
         * @summary 複数のユーザーの支払グループへの所属情報を更新
         * @param {number} paymentGroupId 支払グループID
         * @param {Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>} [addPaymentAffiliationsByPaymentGroupIdRequestInner] リクエスト用の支払グループの所属情報の配列
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePaymentAffiliationsByPaymentGroupId(paymentGroupId: number, addPaymentAffiliationsByPaymentGroupIdRequestInner?: Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>, options?: any): AxiosPromise<Array<PaymentAffiliationUser>> {
            return localVarFp.updatePaymentAffiliationsByPaymentGroupId(paymentGroupId, addPaymentAffiliationsByPaymentGroupIdRequestInner, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PaymentAffiliationApi - object-oriented interface
 * @export
 * @class PaymentAffiliationApi
 * @extends {BaseAPI}
 */
export class PaymentAffiliationApi extends BaseAPI {
    /**
     * 支払グループに複数のユーザーを所属させる
     * @summary 支払グループに複数のユーザーを所属させる
     * @param {number} paymentGroupId 支払グループID
     * @param {Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>} [addPaymentAffiliationsByPaymentGroupIdRequestInner] リクエスト用の支払グループの所属情報の配列
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentAffiliationApi
     */
    public addPaymentAffiliationsByPaymentGroupId(paymentGroupId: number, addPaymentAffiliationsByPaymentGroupIdRequestInner?: Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>, options?: AxiosRequestConfig) {
        return PaymentAffiliationApiFp(this.configuration).addPaymentAffiliationsByPaymentGroupId(paymentGroupId, addPaymentAffiliationsByPaymentGroupIdRequestInner, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 支払グループに所属する全てのユーザーを取得する
     * @summary 支払グループに所属する全てのユーザーを取得
     * @param {number} paymentGroupId 支払グループID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentAffiliationApi
     */
    public getPaymentAffiliationUsersByPaymentGroupId(paymentGroupId: number, options?: AxiosRequestConfig) {
        return PaymentAffiliationApiFp(this.configuration).getPaymentAffiliationUsersByPaymentGroupId(paymentGroupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 複数のユーザーの支払グループへの所属情報を更新する
     * @summary 複数のユーザーの支払グループへの所属情報を更新
     * @param {number} paymentGroupId 支払グループID
     * @param {Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>} [addPaymentAffiliationsByPaymentGroupIdRequestInner] リクエスト用の支払グループの所属情報の配列
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentAffiliationApi
     */
    public updatePaymentAffiliationsByPaymentGroupId(paymentGroupId: number, addPaymentAffiliationsByPaymentGroupIdRequestInner?: Array<AddPaymentAffiliationsByPaymentGroupIdRequestInner>, options?: AxiosRequestConfig) {
        return PaymentAffiliationApiFp(this.configuration).updatePaymentAffiliationsByPaymentGroupId(paymentGroupId, addPaymentAffiliationsByPaymentGroupIdRequestInner, options).then((request) => request(this.axios, this.basePath));
    }
}
