version: '3.9'

services:
  server:
    container_name: dutch-account-server
    build:
      dockerfile: docker/server/Dockerfile
      context: .
    ports:
      - '8000:8000'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    depends_on:
      - db
  db:
    container_name: dutch-account-db
    build:
      dockerfile: docker/db/Dockerfile
      context: .
    volumes:
      - type: volume
        source: dutch-account-db-store
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: 'Asia/Tokyo'

volumes:
  dutch-account-db-store:
