version: '3.9'

services:
  server:
    container_name: dutch-account-server
    build:
      dockerfile: docker/server/Dockerfile
      context: .
    ports:
      - '8000:8000'
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"
    depends_on:
      - db
  db:
    container_name: dutch-account-db
    build:
      dockerfile: docker/db/Dockerfile
      context: .
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: hoge
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: event
      TZ: 'Asia/Tokyo'
