test:
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: user
  password: password
  socket: /tmp/mysql.sock
  database: dutch_account_db
  host: 127.0.0.1
  port: 3306
