/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BulkInsertPaymentRelationByManagementGroupIdRequest } from '../model';
// @ts-ignore
import { PaymentRelation } from '../model';
// @ts-ignore
import { ResponseError } from '../model';
/**
 * PaymentRelationApi - axios parameter creator
 * @export
 */
export const PaymentRelationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 管理グループに紐づく支払グループを作成し複数のユーザーを所属させる
         * @summary 管理グループに紐づく支払グループを作成し複数のユーザーを所属させる
         * @param {string} managementGroupId 管理グループID
         * @param {BulkInsertPaymentRelationByManagementGroupIdRequest} [bulkInsertPaymentRelationByManagementGroupIdRequest] リクエスト用の支払グループと支払グループの所属情報の配列
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkInsertPaymentRelationByManagementGroupId: async (managementGroupId: string, bulkInsertPaymentRelationByManagementGroupIdRequest?: BulkInsertPaymentRelationByManagementGroupIdRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'managementGroupId' is not null or undefined
            assertParamExists('bulkInsertPaymentRelationByManagementGroupId', 'managementGroupId', managementGroupId)
            const localVarPath = `/management_groups/{management_group_id}/payment_relations/bulk_insert`
                .replace(`{${"management_group_id"}}`, encodeURIComponent(String(managementGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            await setApiKeyToObject(localVarHeaderParameter, "access-token", configuration)

            // authentication client required
            await setApiKeyToObject(localVarHeaderParameter, "client", configuration)

            // authentication uid required
            await setApiKeyToObject(localVarHeaderParameter, "uid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkInsertPaymentRelationByManagementGroupIdRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 支払グループに紐づく支払グループを更新し複数のユーザーを所属させる
         * @summary 支払グループに紐づく支払グループを更新し複数のユーザーを所属させる
         * @param {string} managementGroupId 管理グループID
         * @param {string} paymentGroupId 支払グループID
         * @param {BulkInsertPaymentRelationByManagementGroupIdRequest} [bulkInsertPaymentRelationByManagementGroupIdRequest] リクエスト用の支払グループと支払グループの所属情報の配列
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkUpdatePaymentRelationByManagementGroupIdAndPaymentGroupId: async (managementGroupId: string, paymentGroupId: string, bulkInsertPaymentRelationByManagementGroupIdRequest?: BulkInsertPaymentRelationByManagementGroupIdRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'managementGroupId' is not null or undefined
            assertParamExists('bulkUpdatePaymentRelationByManagementGroupIdAndPaymentGroupId', 'managementGroupId', managementGroupId)
            // verify required parameter 'paymentGroupId' is not null or undefined
            assertParamExists('bulkUpdatePaymentRelationByManagementGroupIdAndPaymentGroupId', 'paymentGroupId', paymentGroupId)
            const localVarPath = `/management_groups/{management_group_id}/payment_groups/{payment_group_id}/payment_relations/bulk_update`
                .replace(`{${"management_group_id"}}`, encodeURIComponent(String(managementGroupId)))
                .replace(`{${"payment_group_id"}}`, encodeURIComponent(String(paymentGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            await setApiKeyToObject(localVarHeaderParameter, "access-token", configuration)

            // authentication client required
            await setApiKeyToObject(localVarHeaderParameter, "client", configuration)

            // authentication uid required
            await setApiKeyToObject(localVarHeaderParameter, "uid", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bulkInsertPaymentRelationByManagementGroupIdRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentRelationApi - functional programming interface
 * @export
 */
export const PaymentRelationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentRelationApiAxiosParamCreator(configuration)
    return {
        /**
         * 管理グループに紐づく支払グループを作成し複数のユーザーを所属させる
         * @summary 管理グループに紐づく支払グループを作成し複数のユーザーを所属させる
         * @param {string} managementGroupId 管理グループID
         * @param {BulkInsertPaymentRelationByManagementGroupIdRequest} [bulkInsertPaymentRelationByManagementGroupIdRequest] リクエスト用の支払グループと支払グループの所属情報の配列
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkInsertPaymentRelationByManagementGroupId(managementGroupId: string, bulkInsertPaymentRelationByManagementGroupIdRequest?: BulkInsertPaymentRelationByManagementGroupIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentRelation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkInsertPaymentRelationByManagementGroupId(managementGroupId, bulkInsertPaymentRelationByManagementGroupIdRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 支払グループに紐づく支払グループを更新し複数のユーザーを所属させる
         * @summary 支払グループに紐づく支払グループを更新し複数のユーザーを所属させる
         * @param {string} managementGroupId 管理グループID
         * @param {string} paymentGroupId 支払グループID
         * @param {BulkInsertPaymentRelationByManagementGroupIdRequest} [bulkInsertPaymentRelationByManagementGroupIdRequest] リクエスト用の支払グループと支払グループの所属情報の配列
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async bulkUpdatePaymentRelationByManagementGroupIdAndPaymentGroupId(managementGroupId: string, paymentGroupId: string, bulkInsertPaymentRelationByManagementGroupIdRequest?: BulkInsertPaymentRelationByManagementGroupIdRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaymentRelation>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.bulkUpdatePaymentRelationByManagementGroupIdAndPaymentGroupId(managementGroupId, paymentGroupId, bulkInsertPaymentRelationByManagementGroupIdRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PaymentRelationApi - factory interface
 * @export
 */
export const PaymentRelationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentRelationApiFp(configuration)
    return {
        /**
         * 管理グループに紐づく支払グループを作成し複数のユーザーを所属させる
         * @summary 管理グループに紐づく支払グループを作成し複数のユーザーを所属させる
         * @param {string} managementGroupId 管理グループID
         * @param {BulkInsertPaymentRelationByManagementGroupIdRequest} [bulkInsertPaymentRelationByManagementGroupIdRequest] リクエスト用の支払グループと支払グループの所属情報の配列
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkInsertPaymentRelationByManagementGroupId(managementGroupId: string, bulkInsertPaymentRelationByManagementGroupIdRequest?: BulkInsertPaymentRelationByManagementGroupIdRequest, options?: any): AxiosPromise<PaymentRelation> {
            return localVarFp.bulkInsertPaymentRelationByManagementGroupId(managementGroupId, bulkInsertPaymentRelationByManagementGroupIdRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 支払グループに紐づく支払グループを更新し複数のユーザーを所属させる
         * @summary 支払グループに紐づく支払グループを更新し複数のユーザーを所属させる
         * @param {string} managementGroupId 管理グループID
         * @param {string} paymentGroupId 支払グループID
         * @param {BulkInsertPaymentRelationByManagementGroupIdRequest} [bulkInsertPaymentRelationByManagementGroupIdRequest] リクエスト用の支払グループと支払グループの所属情報の配列
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        bulkUpdatePaymentRelationByManagementGroupIdAndPaymentGroupId(managementGroupId: string, paymentGroupId: string, bulkInsertPaymentRelationByManagementGroupIdRequest?: BulkInsertPaymentRelationByManagementGroupIdRequest, options?: any): AxiosPromise<PaymentRelation> {
            return localVarFp.bulkUpdatePaymentRelationByManagementGroupIdAndPaymentGroupId(managementGroupId, paymentGroupId, bulkInsertPaymentRelationByManagementGroupIdRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PaymentRelationApi - object-oriented interface
 * @export
 * @class PaymentRelationApi
 * @extends {BaseAPI}
 */
export class PaymentRelationApi extends BaseAPI {
    /**
     * 管理グループに紐づく支払グループを作成し複数のユーザーを所属させる
     * @summary 管理グループに紐づく支払グループを作成し複数のユーザーを所属させる
     * @param {string} managementGroupId 管理グループID
     * @param {BulkInsertPaymentRelationByManagementGroupIdRequest} [bulkInsertPaymentRelationByManagementGroupIdRequest] リクエスト用の支払グループと支払グループの所属情報の配列
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentRelationApi
     */
    public bulkInsertPaymentRelationByManagementGroupId(managementGroupId: string, bulkInsertPaymentRelationByManagementGroupIdRequest?: BulkInsertPaymentRelationByManagementGroupIdRequest, options?: AxiosRequestConfig) {
        return PaymentRelationApiFp(this.configuration).bulkInsertPaymentRelationByManagementGroupId(managementGroupId, bulkInsertPaymentRelationByManagementGroupIdRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 支払グループに紐づく支払グループを更新し複数のユーザーを所属させる
     * @summary 支払グループに紐づく支払グループを更新し複数のユーザーを所属させる
     * @param {string} managementGroupId 管理グループID
     * @param {string} paymentGroupId 支払グループID
     * @param {BulkInsertPaymentRelationByManagementGroupIdRequest} [bulkInsertPaymentRelationByManagementGroupIdRequest] リクエスト用の支払グループと支払グループの所属情報の配列
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PaymentRelationApi
     */
    public bulkUpdatePaymentRelationByManagementGroupIdAndPaymentGroupId(managementGroupId: string, paymentGroupId: string, bulkInsertPaymentRelationByManagementGroupIdRequest?: BulkInsertPaymentRelationByManagementGroupIdRequest, options?: AxiosRequestConfig) {
        return PaymentRelationApiFp(this.configuration).bulkUpdatePaymentRelationByManagementGroupIdAndPaymentGroupId(managementGroupId, paymentGroupId, bulkInsertPaymentRelationByManagementGroupIdRequest, options).then((request) => request(this.axios, this.basePath));
    }
}
