/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ResponseError } from '../model';
// @ts-ignore
import { TotalBorrowingAndLending } from '../model';
/**
 * TotalBorrowingAndLendingApi - axios parameter creator
 * @export
 */
export const TotalBorrowingAndLendingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 管理グループに紐づく全てのユーザーの総貸借を取得する
         * @summary 管理グループに紐づく全てのユーザーの総貸借を取得
         * @param {string} managementGroupId 管理グループID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTotalBorrowingAndLendingByManagementGroupId: async (managementGroupId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'managementGroupId' is not null or undefined
            assertParamExists('getTotalBorrowingAndLendingByManagementGroupId', 'managementGroupId', managementGroupId)
            const localVarPath = `/management_groups/{management_group_id}/total_borrowing_and_lendings`
                .replace(`{${"management_group_id"}}`, encodeURIComponent(String(managementGroupId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication accessToken required
            await setApiKeyToObject(localVarHeaderParameter, "access-token", configuration)

            // authentication client required
            await setApiKeyToObject(localVarHeaderParameter, "client", configuration)

            // authentication uid required
            await setApiKeyToObject(localVarHeaderParameter, "uid", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TotalBorrowingAndLendingApi - functional programming interface
 * @export
 */
export const TotalBorrowingAndLendingApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TotalBorrowingAndLendingApiAxiosParamCreator(configuration)
    return {
        /**
         * 管理グループに紐づく全てのユーザーの総貸借を取得する
         * @summary 管理グループに紐づく全てのユーザーの総貸借を取得
         * @param {string} managementGroupId 管理グループID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTotalBorrowingAndLendingByManagementGroupId(managementGroupId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TotalBorrowingAndLending>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTotalBorrowingAndLendingByManagementGroupId(managementGroupId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * TotalBorrowingAndLendingApi - factory interface
 * @export
 */
export const TotalBorrowingAndLendingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TotalBorrowingAndLendingApiFp(configuration)
    return {
        /**
         * 管理グループに紐づく全てのユーザーの総貸借を取得する
         * @summary 管理グループに紐づく全てのユーザーの総貸借を取得
         * @param {string} managementGroupId 管理グループID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTotalBorrowingAndLendingByManagementGroupId(managementGroupId: string, options?: any): AxiosPromise<Array<TotalBorrowingAndLending>> {
            return localVarFp.getTotalBorrowingAndLendingByManagementGroupId(managementGroupId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TotalBorrowingAndLendingApi - object-oriented interface
 * @export
 * @class TotalBorrowingAndLendingApi
 * @extends {BaseAPI}
 */
export class TotalBorrowingAndLendingApi extends BaseAPI {
    /**
     * 管理グループに紐づく全てのユーザーの総貸借を取得する
     * @summary 管理グループに紐づく全てのユーザーの総貸借を取得
     * @param {string} managementGroupId 管理グループID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TotalBorrowingAndLendingApi
     */
    public getTotalBorrowingAndLendingByManagementGroupId(managementGroupId: string, options?: AxiosRequestConfig) {
        return TotalBorrowingAndLendingApiFp(this.configuration).getTotalBorrowingAndLendingByManagementGroupId(managementGroupId, options).then((request) => request(this.axios, this.basePath));
    }
}
