/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AddRemittanceRecordRequest
 */
export interface AddRemittanceRecordRequest {
    /**
     * 送金ユーザーID
     * @type {number}
     * @memberof AddRemittanceRecordRequest
     */
    'from_user_payment_group_id': number;
    /**
     * 着金ユーザーID
     * @type {number}
     * @memberof AddRemittanceRecordRequest
     */
    'to_user_payment_group_id': number;
    /**
     * 送金金額
     * @type {number}
     * @memberof AddRemittanceRecordRequest
     */
    'amount_of_money': number;
    /**
     * 送金日
     * @type {string}
     * @memberof AddRemittanceRecordRequest
     */
    'transferred_on': string;
}

