/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 管理グループ
 * @export
 * @interface ManagementGroup
 */
export interface ManagementGroup {
    /**
     * 管理グループID
     * @type {number}
     * @memberof ManagementGroup
     */
    'id': number;
    /**
     * 管理グループ名
     * @type {string}
     * @memberof ManagementGroup
     */
    'name': string;
}

