/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 購入履歴
 * @export
 * @interface PurchaseRecord
 */
export interface PurchaseRecord {
    /**
     * 購入履歴ID
     * @type {number}
     * @memberof PurchaseRecord
     */
    'id': number;
    /**
     * ユーザー名
     * @type {string}
     * @memberof PurchaseRecord
     */
    'name': string;
    /**
     * 購入金額
     * @type {number}
     * @memberof PurchaseRecord
     */
    'amount_of_money': number;
    /**
     * 購入日
     * @type {string}
     * @memberof PurchaseRecord
     */
    'purchased_on': string;
    /**
     * 購入説明
     * @type {string}
     * @memberof PurchaseRecord
     */
    'description': string;
}

