/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ユーザー支払グループ
 * @export
 * @interface UserPaymentGroup
 */
export interface UserPaymentGroup {
    /**
     * ユーザー支払グループID
     * @type {number}
     * @memberof UserPaymentGroup
     */
    'id': number;
    /**
     * ユーザー名
     * @type {string}
     * @memberof UserPaymentGroup
     */
    'name': string;
    /**
     * 支払割合
     * @type {number}
     * @memberof UserPaymentGroup
     */
    'payment_ratio': number;
}

