/* tslint:disable */
/* eslint-disable */
/**
 * dutch_account_app
 * 割り勘アプリ
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ユーザー
 * @export
 * @interface User
 */
export interface User {
    /**
     * ユーザーID
     * @type {number}
     * @memberof User
     */
    'id': number;
    /**
     * ユーザー名
     * @type {string}
     * @memberof User
     */
    'name': string;
}

