require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  TargetRailsVersion: 7.0.3
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "node_modules/**/*"
    - "db/migrate/**/*"
    - "app/channels/**/*"
    - "config/**/*"
    - "config.ru"
    - "bin/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "Rakefile"
    - "spec/spec_helper.rb"
    - "spec/rails_helper.rb"
Rails:
  Enabled: true

#-----------------------------------------------------------------
# style
#-----------------------------------------------------------------
Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - "app/controllers/api/v1/*"

#-----------------------------------------------------------------
# metrics
#-----------------------------------------------------------------
Metrics/MethodLength:
  Max: 20

#-----------------------------------------------------------------
# rspec
#-----------------------------------------------------------------
RSpec/MultipleExpectations:
  Enabled: false
RSpec/BeEq:
  Enabled: false
RSpec/ExampleLength:
  Max: 15
RSpec/NamedSubject:
  Enabled: false
