# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.1.2'

gem 'rails', '7.0.3'

gem 'bootsnap', require: false
gem 'devise'
gem 'devise_token_auth', git: "https://github.com/lynndylanhurley/devise_token_auth"
gem 'mysql2'
gem 'puma'
gem 'rack-cors'

group :development, :test do
  gem 'debug'
  gem 'factory_bot_rails'
  gem 'pry-byebug'
  gem 'rspec-rails'
end

group :development do
  gem 'bullet'
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end

group :test do
  gem 'shoulda-matchers'
end
