openapi: 3.0.0
info:
  version: 1.0.0
  title: dutch_account_app
  description: 割り勘アプリ
servers:
  - url: http://localhost:8000/api/v1
    description: 開発環境
tags:
  - name: paymentGroup
  - name: paymentAffiliation
  - name: debtRecord
  - name: user
security:
  - accessToken: []
    uid: []
    client: []
paths:
  /payment_groups:
    get:
      tags:
        - paymentGroup
      summary: 全ての支払グループを取得
      description: 全ての支払グループを取得する
      operationId: getPaymentGroups
      responses:
        200:
          description: 取得が成功した時のレスポンス
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaymentGroup"
        401:
          $ref: "#/components/responses/Unauthorized"
        500:
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - paymentGroup
      summary: 支払グループを作成
      description: 支払グループを作成する
      operationId: addPaymentGroup
      requestBody:
        $ref: "#/components/requestBodies/PaymentGroupBody"
      responses:
        201:
          description: 作成が成功した時のレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentGroup"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        500:
          $ref: "#/components/responses/InternalServerError"
  /payment_groups/{payment_group_id}:
    parameters:
      - $ref: "#/components/parameters/PaymentGroupId"
    get:
      tags:
        - paymentGroup
      summary: 支払グループを取得
      description: 支払グループを取得する
      operationId: getPaymentGroupByPaymentGroupId
      responses:
        200:
          description: 取得が成功した時のレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentGroup"
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
    put:
      tags:
        - paymentGroup
      summary: 支払グループを更新
      description: 支払グループを更新する
      operationId: updatePaymentGroupByPaymentGroupId
      requestBody:
        $ref: "#/components/requestBodies/PaymentGroupBody"
      responses:
        200:
          description: 更新が成功した時のレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentGroup"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
    delete:
      tags:
        - paymentGroup
      summary: 支払グループを削除
      description: 支払グループを削除する
      operationId: deletePaymentGroupByPaymentGroupId
      responses:
        204:
          $ref: "#/components/responses/NoContent"
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
  /payment_groups/{payment_group_id}/payment_affiliation_users:
    parameters:
      - $ref: "#/components/parameters/PaymentGroupId"
    get:
      tags:
        - paymentAffiliation
      summary: ある支払グループに所属する全てのユーザーを取得
      description: ある支払グループに所属する全てのユーザーを取得する
      operationId: getPaymentAffiliationUsersByPaymentGroupId
      responses:
        200:
          description: 取得が成功した時のレスポンス
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaymentAffiliationUser"
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
  /payment_groups/{payment_group_id}/payment_affiliations/bulk_insert:
    parameters:
      - $ref: "#/components/parameters/PaymentGroupId"
    post:
      tags:
        - paymentAffiliation
      summary: ある支払グループに複数のユーザーを所属させる
      description: ある支払グループに複数のユーザーを所属させる
      operationId: addPaymentAffiliationsByPaymentGroupId
      requestBody:
        $ref: "#/components/requestBodies/PaymentAffiliationsBody"
      responses:
        201:
          description: 作成が成功した時のレスポンス
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaymentAffiliationUser"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
  /payment_groups/{payment_group_id}/payment_affiliations/bulk_update:
    parameters:
      - $ref: "#/components/parameters/PaymentGroupId"
    put:
      tags:
        - paymentAffiliation
      summary: 複数のユーザーのある支払グループへの所属情報を更新
      description: 複数のユーザーのある支払グループへの所属情報を更新する
      operationId: updatePaymentAffiliationsByPaymentGroupId
      requestBody:
        $ref: "#/components/requestBodies/PaymentAffiliationsBody"
      responses:
        200:
          description: 更新が成功した時のレスポンス
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PaymentAffiliationUser"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
  /users/{lending_user_id}/borrowing_user_debt_records:
    parameters:
      - $ref: "#/components/parameters/LendingUserId"
    get:
      tags:
        - debtRecord
      summary: 貸主に紐づく全ての借金履歴及び借主名を取得
      description: 貸主に紐づく全ての借金履歴及び借主名を取得する
      operationId: getBorrowingUserDebtRecordsByLendingUserId
      responses:
        200:
          description: 取得が成功した時のレスポンス
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BorrowingUserDebtRecord"
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
  /users/debt_records/bulk_insert:
    post:
      tags:
        - debtRecord
      summary: 借金履歴を複数作成
      description: 借金履歴を複数作成する
      operationId: addDebtRecords
      requestBody:
        $ref: "#/components/requestBodies/DebtRecordsBody"
      responses:
        201:
          description: 作成が成功した時のレスポンス
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserDebtRecord"
        400:
          $ref: "#/components/responses/BadRequest"
        401:
          $ref: "#/components/responses/Unauthorized"
        500:
          $ref: "#/components/responses/InternalServerError"
  /user_debt_records/{debt_record_id}:
    parameters:
      - $ref: "#/components/parameters/DebtRecordId"
    get:
      tags:
        - debtRecord
      summary: 借金履歴及びユーザー名を取得
      description: 借金履歴及びユーザー名を取得する
      operationId: getUserDebtRecordByDebtRecordId
      responses:
        200:
          description: 取得が成功した時のレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDebtRecord"
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
  /debt_records/{debt_record_id}:
    parameters:
      - $ref: "#/components/parameters/DebtRecordId"
    delete:
      tags:
        - debtRecord
      summary: 借金履歴を削除
      description: 借金履歴を削除する
      operationId: deleteDebtRecordByDebtRecordId
      responses:
        204:
          $ref: "#/components/responses/NoContent"
        401:
          $ref: "#/components/responses/Unauthorized"
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
  /sign_up:
    post:
      tags:
        - user
      summary: サインアップ
      description: サインアップする
      operationId: signUp
      security: []
      requestBody:
        $ref: "#/components/requestBodies/SignUpBody"
      responses:
        200:
          description: サインアップに成功した時のレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          headers:
            access-token:
              $ref: "#/components/headers/access-token"
            uid:
              $ref: "#/components/headers/uid"
            client:
              $ref: "#/components/headers/client"
        422:
          $ref: "#/components/responses/UnprocessableEntity"
        500:
          $ref: "#/components/responses/InternalServerError"
  /sign_in:
    post:
      tags:
        - user
      summary: サインイン
      description: サインインする
      operationId: signIn
      security: []
      requestBody:
        $ref: "#/components/requestBodies/SignInBody"
      responses:
        200:
          description: サインインに成功した時のレスポンス
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          headers:
            access-token:
              $ref: "#/components/headers/access-token"
            uid:
              $ref: "#/components/headers/uid"
            client:
              $ref: "#/components/headers/client"
        401:
          $ref: "#/components/responses/Unauthorized"
        500:
          $ref: "#/components/responses/InternalServerError"
  /sign_out:
    post:
      tags:
        - user
      summary: サインアウト
      description: サインアウトする
      operationId: signOut
      responses:
        200:
          description: サインアウトに成功した時のレスポンス
          content:
            {}
        404:
          $ref: "#/components/responses/NotFound"
        500:
          $ref: "#/components/responses/InternalServerError"
components:
  responses:
    NoContent:
      description: リクエストが成功し、返すリソースがない時のレスポンス
      content:
        {}
    BadRequest:
      description: リクエストパラメーターに不備がある時のレスポンス
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            messages: [リクエストパラメーターに不備があります]
    Unauthorized:
      description: 認証されていない時のレスポンス
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            messages: [アクセス権限がありません]
    NotFound:
      description: リクエストされたリソースが存在しない時のレスポンス
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            messages: [ページが見つかりません]
    UnprocessableEntity:
      description: リクエストされた指示を処理できなかった時のレスポンス
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            messages: [このアカウントはすでに存在しています]
    InternalServerError:
      description: サーバーでエラーが発生している時のレスポンス
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            messages: [サーバーでエラーが発生しています]
  headers:
    access-token:
      description: パスワードとして機能する
      schema:
        type: string
    uid:
      description: ユーザーを識別するために使用する
      schema:
        type: string
    client:
      description: 異なるクライアントで認証を行うために使用する
      schema:
        type: string
  schemas:
    Error:
      description: エラー
      type: object
      required:
        - messages
      properties:
        messages:
          type: array
          items:
            type: string
          description: エラーメッセージ
          example: エラーが発生しました
    User:
      description: ユーザー
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: ユーザーID
          example: 1
        name:
          type: string
          description: ユーザー名
          example: 太郎
    PaymentGroup:
      description: 支払グループ
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          description: 支払グループID
          example: 1
        name:
          type: string
          description: 支払グループ名
          example: 家族
    PaymentAffiliationUser:
      description: ある支払グループに所属するユーザー
      type: object
      required:
        - id
        - user_name
        - ratio
      properties:
        id:
          type: integer
          format: int64
          description: 所属ID
          example: 1
        user_name:
          type: string
          description: ユーザー名
          example: 太郎
        ratio:
          type: number
          format: float
          description: 支払割合
          example: 0.4
    UserDebtRecord:
      description: 借金履歴及びユーザー名
      type: object
      required:
        - id
        - lending_user_name
        - borrowing_user_name
        - amount_of_money
        - description
        - transacted_on
      properties:
        id:
          type: integer
          format: int64
          description: 借金履歴ID
          example: 1
        lending_user_name:
          type: string
          description: 貸主名
          example: 太郎
        borrowing_user_name:
          type: string
          description: 借主名
          example: 次郎
        amount_of_money:
          type: integer
          format: int32
          description: 金額
          example: 3000
        description:
          type: string
          description: 説明
          example: 食材
        transacted_on:
          type: string
          format: date
          description: 取引日
          example: "2022-01-01"
    BorrowingUserDebtRecord:
      description: 借金履歴及び借主名
      type: object
      required:
        - id
        - borrowing_user_name
        - amount_of_money
        - description
        - transacted_on
      properties:
        id:
          type: integer
          format: int64
          description: 借金履歴ID
          example: 1
        borrowing_user_name:
          type: integer
          format: int64
          description: 借主名
          example: 次郎
        amount_of_money:
          type: integer
          format: int32
          description: 金額
          example: 3000
        description:
          type: string
          description: 説明
          example: 食材
        transacted_on:
          type: string
          format: date
          description: 取引日
          example: "2022-01-01"
  requestBodies:
    PaymentGroupBody:
      description: リクエスト用の支払グループ
      content:
        application/json:
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
                description: 支払グループ名
                example: 家族
    PaymentAffiliationsBody:
      description: リクエスト用の所属の配列
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              required:
                - user_id
                - ratio
              properties:
                user_id:
                  type: integer
                  format: int64
                  description: ユーザーID
                  example: 1
                ratio:
                  type: number
                  format: float
                  description: 支払割合
                  example: 0.4
    DebtRecordsBody:
      description: リクエスト用の借金履歴の配列
      content:
        application/json:
          schema:
            type: array
            items:
              type: object
              required:
                - lending_user_id
                - borrowing_user_id
                - amount_of_money
                - description
                - transacted_on
              properties:
                lending_user_id:
                    type: integer
                    format: int64
                    description: 貸主ID
                    example: 1
                borrowing_user_id:
                    type: integer
                    format: int64
                    description: 借主ID
                    example: 2
                amount_of_money:
                  type: integer
                  format: int32
                  description: 金額
                  example: 3000
                description:
                  type: string
                  description: 説明
                  example: 食材
                transacted_on:
                  type: string
                  format: date
                  description: 取引日
                  example: "2022-01-01"
    SignUpBody:
      description: サインアップ用のユーザー
      content:
        application/json:
          schema:
            type: object
            required:
              - name
              - email
              - password
              - password_confirmation
            properties:
              name:
                type: string
                description: ユーザー名
                example: 太郎
              email:
                type: string
                format: email
                description: メールアドレス
                example: email@example.com
              password:
                type: string
                format: password
                description: パスワード
                example: password
              password_confirmation:
                type: string
                format: password
                description: 確認用パスワード
                example: password
    SignInBody:
      description: サインイン用のユーザー
      content:
        application/json:
          schema:
            type: object
            required:
              - email
              - password
            properties:
              email:
                type: string
                format: email
                description: メールアドレス
                example: email@example.com
              password:
                type: string
                format: password
                description: パスワード
                example: password
  parameters:
    LendingUserId:
      name: lending_user_id
      in: path
      description: 貸主ID
      required: true
      schema:
        type: integer
        format: int64
        example: 1
    PaymentGroupId:
      name: payment_group_id
      in: path
      description: 支払グループID
      required: true
      schema:
        type: integer
        format: int64
        example: 1
    DebtRecordId:
      name: debt_record_id
      in: path
      description: 借金履歴ID
      required: true
      schema:
        type: integer
        format: int64
        example: 1
  securitySchemes:
    accessToken:
      type: apiKey
      in: header
      name: access-token
    uid:
      type: apiKey
      in: header
      name: uid
    client:
      type: apiKey
      in: header
      name: client
