openapi: 3.0.0
info:
  version: 1.0.0
  title: dutch-account-app
  description: 割り勘計算アプリ
servers:
  - url: http://localhost:3000/api
    description: 開発環境
tags:
  - name: user
paths:
  /users:
    get:
      tags:
        - user
      summary: 全ユーザ情報取得API
      description: 全てのユーザ情報を取得する
      responses:
        200:
          description: 全てのユーザー情報
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        500:
          $ref: "#/components/responses/InternalServerError"
    post:
      tags:
        - user
      summary: ユーザ作成API
      description: ユーザを作成する
      requestBody:
        $ref: "#/components/requestBodies/UserBody"
      responses:
        201:
          description: 追加されたユーザ情報
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        400:
          $ref: "#/components/responses/BadRequest"
        500:
          $ref: "#/components/responses/InternalServerError"
components:
  responses:
    BadRequest:
      description: リクエストパラメーターに不備がある時のレスポンス
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: 400
            message: リクエストパラメーターに不備があります
    InternalServerError:
      description: サーバー側でエラーが発生している時のレスポンス
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            code: 500
            message: サーバーでエラーが発生しています
  schemas:
    Error:
      description: エラー情報
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: HTTPステータスコード
        message:
          type: string
          description: エラーメッセージ
    User:
      description: ユーザ情報
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
          example: 1
          description: ユーザID
        name:
          type: string
          example: 太郎
          description: ユーザ名
  requestBodies:
    UserBody:
      description: リクエストユーザ情報
      content:
        application/json:
          schema:
            type: object
            required:
              - name
            properties:
              name:
                type: string
                example: 太郎
                description: ユーザ名
