openapi: 3.0.0
info:
  version: "1.0.0"
  title: "dutch-account-app"
  description: "割り勘計算アプリ"
tags:
- name: "user"
paths:
  /users:
    get:
      tags:
      - "user"
      summary: "全ユーザ情報取得API"
      description: "全てのユーザ情報を取得する"
      responses:
        200:
          description: "成功時のレスポンス"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: "integer"
                      format: "int64"
                      example: 1
                    name:
                      type: "string"
                      example: "太郎"
